
Epoch  0: 0.75, 0.52, 0.74, 0.82
Epoch  1: 0.49, 0.55, 0.82, 0.79
Epoch  2: 0.44, 0.46, 0.84, 0.82
Epoch  3: 0.41, 0.49, 0.85, 0.81
Epoch  4: 0.40, 0.41, 0.86, 0.85
Epoch  5: 0.38, 0.61, 0.86, 0.76
Epoch  6: 0.37, 0.40, 0.87, 0.85
Epoch  7: 0.36, 0.37, 0.87, 0.86
Epoch  8: 0.35, 0.38, 0.87, 0.87
Epoch  9: 0.34, 0.50, 0.88, 0.80
Epoch 10: 0.33, 0.38, 0.88, 0.86
Epoch 11: 0.33, 0.37, 0.88, 0.86
Epoch 12: 0.32, 0.42, 0.88, 0.84
Epoch 13: 0.31, 0.41, 0.89, 0.85
Epoch 14: 0.31, 0.34, 0.89, 0.88
Epoch 15: 0.30, 0.37, 0.89, 0.87
Epoch 16: 0.30, 0.35, 0.89, 0.87
Epoch 17: 0.29, 0.43, 0.89, 0.83
Epoch 18: 0.29, 0.41, 0.90, 0.85
Epoch 19: 0.28, 0.34, 0.90, 0.88
Epoch 20: 0.28, 0.33, 0.90, 0.88
Epoch 21: 0.28, 0.36, 0.90, 0.87
Epoch 22: 0.27, 0.38, 0.90, 0.86
Epoch 23: 0.27, 0.34, 0.90, 0.88
Epoch 24: 0.26, 0.35, 0.90, 0.87
Epoch 25: 0.26, 0.32, 0.90, 0.88
Epoch 26: 0.26, 0.40, 0.91, 0.86
Epoch 27: 0.26, 0.38, 0.91, 0.87
Epoch 28: 0.25, 0.35, 0.91, 0.87
Epoch 29: 0.25, 0.34, 0.91, 0.87
Epoch 30: 0.24, 0.32, 0.91, 0.88
Epoch 31: 0.24, 0.31, 0.91, 0.89
Epoch 32: 0.24, 0.31, 0.91, 0.89
Epoch 33: 0.23, 0.31, 0.91, 0.89
Epoch 34: 0.23, 0.33, 0.91, 0.88
Epoch 35: 0.23, 0.37, 0.92, 0.87
Epoch 36: 0.23, 0.34, 0.92, 0.88
Epoch 37: 0.22, 0.33, 0.92, 0.88
Epoch 38: 0.22, 0.32, 0.92, 0.89
Epoch 39: 0.22, 0.31, 0.92, 0.89
Epoch 40: 0.22, 0.36, 0.92, 0.87
Epoch 41: 0.21, 0.36, 0.92, 0.87
Epoch 42: 0.21, 0.36, 0.92, 0.87
Epoch 43: 0.21, 0.31, 0.92, 0.89
Epoch 44: 0.21, 0.37, 0.92, 0.87
Epoch 45: 0.21, 0.50, 0.93, 0.82
Epoch 46: 0.20, 0.32, 0.93, 0.89
Epoch 47: 0.20, 0.38, 0.93, 0.87
Epoch 48: 0.20, 0.34, 0.93, 0.88
Epoch 49: 0.20, 0.32, 0.93, 0.89
Epoch 50: 0.19, 0.36, 0.93, 0.87
Epoch 51: 0.19, 0.33, 0.93, 0.88
Epoch 52: 0.19, 0.32, 0.93, 0.89
Epoch 53: 0.19, 0.34, 0.93, 0.88
Epoch 54: 0.19, 0.33, 0.93, 0.89
Epoch 55: 0.18, 0.37, 0.93, 0.87
Epoch 56: 0.18, 0.33, 0.93, 0.89
Epoch 57: 0.18, 0.33, 0.94, 0.89
KeyboardInterrupt
Process wandb_internal:
Traceback (most recent call last):
  File "/opt/conda/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/opt/conda/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/conda/lib/python3.9/site-packages/wandb/sdk/internal/internal.py", line 162, in wandb_internal
    thread.join()
  File "/opt/conda/lib/python3.9/threading.py", line 1053, in join
    self._wait_for_tstate_lock()
  File "/opt/conda/lib/python3.9/threading.py", line 1069, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):
KeyboardInterrupt
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/conda/lib/python3.9/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/opt/conda/lib/python3.9/multiprocessing/spawn.py", line 129, in _main
    return self._bootstrap(parent_sentinel)
  File "/opt/conda/lib/python3.9/multiprocessing/process.py", line 333, in _bootstrap
    threading._shutdown()
  File "/opt/conda/lib/python3.9/threading.py", line 1448, in _shutdown
    lock.acquire()
KeyboardInterrupt
Exception in thread ChkStopThr:
Traceback (most recent call last):
  File "/opt/conda/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/opt/conda/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/conda/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 167, in check_status
    status_response = self._interface.communicate_stop_status()
  File "/opt/conda/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 114, in communicate_stop_status
    resp = self._communicate_stop_status(status)
  File "/opt/conda/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 387, in _communicate_stop_status
    resp = self._communicate(req, local=True)
  File "/opt/conda/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 222, in _communicate
Exception in thread NetStatThr:
Traceback (most recent call last):
  File "/opt/conda/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    return self._communicate_async(rec, local=local).get(timeout=timeout)
  File "/opt/conda/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 227, in _communicate_async
        self.run()
  File "/opt/conda/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/conda/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 149, in check_network_status
    raise Exception("The wandb backend process has shutdown")
Exception: The wandb backend process has shutdown
status_response = self._interface.communicate_network_status()
  File "/opt/conda/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 125, in communicate_network_status
    resp = self._communicate_network_status(status)
  File "/opt/conda/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 397, in _communicate_network_status
    resp = self._communicate(req, local=True)
  File "/opt/conda/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 222, in _communicate
    return self._communicate_async(rec, local=local).get(timeout=timeout)
  File "/opt/conda/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 227, in _communicate_async
    raise Exception("The wandb backend process has shutdown")
Exception: The wandb backend process has shutdown
Error in callback <function _WandbInit._resume_backend at 0x7f409864cf70> (for pre_run_cell):
Error in callback <function _WandbInit._pause_backend at 0x7f4098473820> (for post_run_cell):